FROM node:10

RUN mkdir -p /app/src/client

COPY ./package.json /app
COPY ./package-lock.json /app
COPY ./params.js /app
COPY ./webpack.config.js /app
COPY ./index.html /app
COPY ./src/server /app/src/server

WORKDIR /app

RUN npm install

EXPOSE 3004

CMD npm run srv-dev