FROM node:14.9.0-alpine as build
ARG server_host
ENV REACT_APP_SERVER_HOST=$server_host

WORKDIR /redtetris/client/
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run client-dist

FROM nginx:stable-alpine
COPY --from=build /redtetris/client/build /usr/share/nginx/html
COPY ./resources/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]