FROM node:14.9.0-alpine as build
ENV REACT_APP_BACK_HOST=http://redtetris.co
ENV REACT_APP_BACK_PORT=3004

WORKDIR /redtetris/client/
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run client-dist

FROM nginx:stable-alpine
COPY --from=build /redtetris/client/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]